[general]
import = [
 "~/.config/alacritty/themes/tokyo-night.toml"
]

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
opacity = 0.7

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
